apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: development
  annotations:
    cert-manager.io/issuer: letsencrypt-api
spec: 
  tls:
    - hosts:
      - api.jdnielss.my.id
      secretName: letsencrypt-api
  rules:
    - host: api.jdnielss.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-api-service # samain di Serive app
                port:
                  number: 8080
  ingressClassName: nginx