apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: development
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec: 
  tls:
    - hosts:
      - kube.jdnielss.my.id
      secretName: letsencrypt-nginx
  rules:
    - host: kube.jdnielss.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service # samain di Serive app
                port:
                  number: 80
  ingressClassName: nginx