apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  namespace: development
spec:
  selector:
    app: go-api-service
  ports:
    - name: go-api-service
      port: 80
      targetPort: 80