apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-argo
  namespace: argocd
spec:
  acme:
    email: jdnielss@mailinator.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-argo-private-key
    solvers:
      - http01:
          ingress:
            class: nginx