---
apiVersion: networking.istio.io/v1alpha3
kind: DestionationRule
metadata:
  name: nginx
  namespace: development
spec:
  host: nginx
  subsets:
    - name: v1
      labels:
        app: nginx
        version: v1